name: C++ checks

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-style
  cancel-in-progress: true

jobs:
  cxx-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: install conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: install GCC 15
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda create -y -n gcc15 -c conda-forge gcc=15.2.0 gxx=15.2.0

      - name: Set environment variables
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate gcc15
          echo "CC=$(which gcc)" >> $GITHUB_ENV
          echo "CXX=$(which g++)" >> $GITHUB_ENV
          echo "$(dirname $(which gcc))" >> $GITHUB_PATH

      - name: report GCC version
        run: gcc --version

      - name: check the code in examples
        run: |
          ./test.py
